import { and, desc, eq, or } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertUser, marketplaceSkills, users, workspaceStates } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {}; const textFields = ["name", "email", "loginMethod"] as const; for (const field of textFields) { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } } if (user.lastSignedIn !== undefined) { values.lastSignedIn = user.lastSignedIn; updateSet.lastSignedIn = user.lastSignedIn; } if (user.role !== undefined) { values.role = user.role; updateSet.role = user.role; } else if (user.openId === ENV.ownerOpenId) { values.role = "admin"; updateSet.role = "admin"; } values.lastSignedIn ??= new Date(); if (!Object.keys(updateSet).length) updateSet.lastSignedIn = new Date(); await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function getWorkspaceState(visitorId: string) { const db = await getDb(); if (!db) return undefined; const row = (await db.select().from(workspaceStates).where(eq(workspaceStates.visitorId, visitorId)).limit(1))[0]; if (!row) return undefined; try { return { messages: JSON.parse(row.messagesJson), memory: JSON.parse(row.memoryJson), skills: JSON.parse(row.skillsJson), secrets: JSON.parse(row.secretsJson), updatedAt: row.updatedAt }; } catch { return undefined; } }
export async function saveWorkspaceState(visitorId: string, state: { messages: unknown[]; memory: unknown[]; skills: unknown[]; secrets: unknown[] }) { const db = await getDb(); if (!db) return false; const values = { visitorId, messagesJson: JSON.stringify(state.messages), memoryJson: JSON.stringify(state.memory), skillsJson: JSON.stringify(state.skills), secretsJson: JSON.stringify(state.secrets) }; await db.insert(workspaceStates).values(values).onDuplicateKeyUpdate({ set: { ...values, updatedAt: new Date() } }); return true; }
export async function listMarketplaceSkills(visitorId?: string) { const db = await getDb(); if (!db) return []; const visible = visitorId ? or(eq(marketplaceSkills.status, "approved"), eq(marketplaceSkills.visitorId, visitorId)) : eq(marketplaceSkills.status, "approved"); return db.select().from(marketplaceSkills).where(and(visible, eq(marketplaceSkills.visibility, "public"))).orderBy(desc(marketplaceSkills.createdAt)); }
export async function publishMarketplaceSkill(input: { visitorId: string; title: string; description?: string; content: string; visibility: "private" | "public" }) { const db = await getDb(); if (!db) return undefined; const result = await db.insert(marketplaceSkills).values({ ...input, description: input.description || null, status: input.visibility === "public" ? "pending" : "approved" }); return result[0]?.insertId; }
export async function reviewMarketplaceSkill(id: number, status: "approved" | "rejected", reviewerNote?: string) { const db = await getDb(); if (!db) return false; await db.update(marketplaceSkills).set({ status, reviewerNote: reviewerNote || null }).where(eq(marketplaceSkills.id, id)); return true; }
